// THIS JAVASCRIPT ANIMATION IS DIRECTLY FROM THE W3SCHOOLS TAB GALLERY EXAMPLE, 
// HOWEVER I OMITTED PARTS OF THE CODE THAT DID NOT SERVE ANY PURPOSE IN MY WEBSITE.

function myFunction(imgs) {
  // GET IMAGE
  var expandImg = document.getElementById("expandedImg");
  // CONNECT TAB IMAGE TO EXPANDED IMAGE THROUGH SAME SOURCE
  expandImg.src = imgs.src;
}
